version: '3.7'

services:
    api-nginx:
        image: nginx:alpine-slim
        container_name: api-nginx
        depends_on:
            - api-php
        ports:
            - "8005:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - whiteboard

    api-php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api-php
        restart: always
        volumes:
            - .:/var/www/html
        ports:
            - "9000"
        networks:
            - whiteboard

    redis:
        image: "redis:alpine"
        container_name: redis
        command: redis-server --requirepass secret
        ports:
            - "6379"
        networks:
            - whiteboard

    node:
        image: "node:alpine"
        container_name: node
        command: sh -c "while true; do sleep 1000; done"
        networks:
            - whiteboard

    pgsql:
        image: "postgres:12-alpine"
        container_name: pgsql
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=whiteboard
        ports:
            - "5432"
        networks:
            - whiteboard

networks:
    whiteboard:
        driver: bridge
